---
title: "Final Predation kernels"
output:
  pdf_document: default
  html_document: default
date: "2024-07-22"
---

```{r, include=FALSE}

fl <- function(l, alpha, ll, ul, lr, ur) {
  dl <- ll - l
  dr <- l - lr
  fl_values <- exp(alpha * l) / (1 + exp(ul * dl)) / (1 + exp(ur * dr))
  
  # Debugging output
  if (any(!is.finite(fl_values))) {
    print("Non-finite fl values found")
    print(fl_values)
  }
  
  return(fl_values)
}

## Define the truncated exponential PDF with debugging
dtexp <- function(l, alpha, ll, ul, lr, ur) {
  fl_values <- fl(l, alpha, ll, ul, lr, ur)
  
  integral_result <- tryCatch(
    integrate(fl, 0, 30, alpha = alpha, ll = ll, ul = ul, lr = lr, ur = ur),
    error = function(e) {
      print("Integration failed")
     print(e)
      return(NULL)
    }
   )
   
   if (is.null(integral_result)) {
     return(rep(NA, length(l)))
   }
   
   d <- fl_values / integral_result$value
   
  # Debugging output
  if (any(!is.finite(d))) {
    print("Non-finite d values found")
    print(d)
  }
  
  return(d)
}

 #Define the MLE function with debugging
mle_texp <- function(df) {
  loglik <- function(alpha, ll, ul, lr, ur) {
    L <- dtexp(df$l, alpha, ll, ul, lr, ur)
    
    # Debugging output
    if (any(!is.finite(L) | L <= 0)) {
     print("Non-finite or non-positive L values found")
      print(which(!is.finite(L) | L <= 0))
      return(Inf)
    }
    
    -sum(log(L) * df$weight_numbers)
  }
  
  result <- tryCatch(
    mle2(loglik, start = list(
      alpha = 0.5,
      ll = min(df$l),
      lr = max(df$l),
      ul = 5,
      ur = 5
    ), method = "L-BFGS-B", control = list(maxit = 10000)),
    error = function(e) {
      print("MLE fitting failed")
      print(e)
      return(NULL)
    }
  )
  
  return(result)
}


```

```{r, include=FALSE}
library(ggplot2)
library(bbmle)
library(dplyr)
library(mclust)
load("C:/Users/lucab/Downloads/stomach_dataset.Rdata") 
```

##Cod

```{r}
dig <- 1
sprat <- stom_df%>%filter(pred_taxa=="Gadus morhua")
sprat <- sprat%>%filter(nprey_perpred>0)
sprat$weight_numbers <- sprat$nprey_perpred
sprat$weight_biomass <- sprat$nprey_perpred*sprat$prey_ind_weight_g^dig
stomach <- sprat
stomach <- stomach%>%mutate(l=log(ppmr))%>%filter(!is.na(l))

est <- mle_texp(stomach)

biomassco <- est@coef

numberestco <- biomassco

grid = seq(min(stomach$l), max(stomach$l), length.out = 200)
dist <- dtexp(grid, alpha = (numberestco[1]), ll = numberestco[2], ul = numberestco[3], lr = numberestco[4], ur = numberestco[5])
numberdist <- data.frame(l=grid, Density=dist)
dist <- dtexp(grid, alpha = (numberestco[1]-1), ll = numberestco[2], ul = numberestco[3], lr = numberestco[4], ur = numberestco[5])
biomassdist <- data.frame(l=grid, Density=dist)
#now plot these two together

stomach <- stomach %>% mutate(biomass = nprey_perpred * prey_ind_weight_g)

ggplot(stomach) + 
  geom_density(aes(l, weight=weight_numbers))+
  geom_density(aes(l, weight=biomass))+
 xlab("Log of predator/prey mass ratio") + 
  geom_line(aes(l, Density), data = biomassdist, color = "red")+
  geom_line(aes(l, Density), data = numberdist, color = "blue")+
  xlim(0,13)+
  ggtitle("Cod - Fit to number, shift to diet")

```

##Blue Whiting

```{r}
sprat <- stom_df%>%filter(pred_taxa=="Micromesistius poutassou")
sprat <- sprat%>%filter(nprey_perpred>0)
stomach <- sprat
stomach <- stomach%>%mutate(l=log(ppmr))%>%filter(!is.na(l))
stomach <- stomach %>% mutate(weight_numbers = nprey_perpred * prey_ind_weight_g)
stomach$biomass <- stomach$nprey_perpred*stomach$prey_ind_weight_g

est <- mle_texp(stomach)
biomassestco <- est@coef

stomach <- stomach %>% mutate(weight_numbers = nprey_perpred)
grid = seq(0, 30, length.out = 200)

dist <- dtexp(grid, alpha = (biomassestco[1]), ll = biomassestco[2], ul = biomassestco[3], lr = biomassestco[4], ur = biomassestco[5])
biomassdist <- data.frame(l=grid, Density=dist)

shiftdist <- dtexp(grid, alpha = (biomassestco[1]+1), ll = biomassestco[2], ul = biomassestco[3], lr = biomassestco[4], ur = biomassestco[5])
shiftbiomassdist <- data.frame(l=grid, Density=shiftdist)

ggplot(stomach) + 
  geom_density(aes(l, weight=weight_numbers))+
  geom_density(aes(l, weight=biomass))+
 xlab("Log of predator/prey mass ratio") + 
  geom_line(aes(l, Density), data = biomassdist, color = "red")+
  geom_line(aes(l, Density), data = shiftbiomassdist, color = "blue")+
  ggtitle("Blue Whiting - Fitted to Biomass, shift to number")

```

##Common Dab

```{r}

sprat <- stom_df%>%filter(pred_taxa=="Limanda limanda")
sprat <- sprat%>%filter(nprey_perpred>0)
stomach <- sprat
stomach <- stomach%>%mutate(l=log(ppmr))%>%filter(!is.na(l))
stomach <- stomach %>% mutate(weight_numbers = nprey_perpred)
stomach$biomass <- stomach$nprey_perpred*stomach$prey_ind_weight_g

est <- mle_texp(stomach)
biomassestco <- est@coef

stomach <- stomach %>% mutate(weight_numbers = nprey_perpred)
grid = seq(0, 30, length.out = 200)

dist <- dtexp(grid, alpha = (biomassestco[1]), ll = biomassestco[2], ul = biomassestco[3], lr = biomassestco[4], ur = biomassestco[5])
biomassdist <- data.frame(l=grid, Density=dist)

shiftdist <- dtexp(grid, alpha = (biomassestco[1]-1), ll = biomassestco[2], ul = biomassestco[3], lr = biomassestco[4], ur = biomassestco[5])
shiftbiomassdist <- data.frame(l=grid, Density=shiftdist)

ggplot(stomach) + 
  geom_density(aes(l, weight=weight_numbers))+
  geom_density(aes(l, weight=biomass))+
 xlab("Log of predator/prey mass ratio") + 
  geom_line(aes(l, Density), data = biomassdist, color = "blue")+
  geom_line(aes(l, Density), data = shiftbiomassdist, color = "red")+
  ggtitle("Common Dab - Fitted to number, shift to biomass")

```

```{r, return=FALSE}
repeat_elements <- function(data, weights) {

    valid_indices <- !is.na(data) & !is.na(weights)
  data <- data[valid_indices]
  weights <- weights[valid_indices]
  
  final_vector <- c()

  for (i in seq_along(data)) {

    rounded_weight <- round(weights[i])

    repeated_values <- rep(data[i], times = rounded_weight)

    final_vector <- c(final_vector, repeated_values)
  }
  
  return(final_vector)
}
```

##European Hake

```{r}
sprat <- stom_df%>%filter(pred_taxa=="Merluccius merluccius")
spratnu <- repeat_elements(log(sprat$ppmr), sprat$nprey_perpred)
sprat$weight_numbers <- sprat$nprey_perpred
sprat$weight_biomass <- sprat$nprey_perpred*sprat$prey_ind_weight_g^dig
gmm <- densityMclust(spratnu, G=2)

dplot <- data.frame(x=gmm[["data"]], density=gmm[["density"]])


newspratdens <- gmm[["density"]]*exp(-dig*gmm[["data"]])
shifted_pdf_normalized <- newspratdens / sum(newspratdens) 

#making new dataframe
dplot2 <- data.frame(x=gmm[["data"]], density=shifted_pdf_normalized)


(numbfit <- ggplot() +
    geom_density(data=sprat, aes(log(ppmr), weight=weight_numbers))+
  geom_line(data=dplot, aes(x = x, y = density), color="red") +
    geom_density(data=sprat, aes(log(ppmr), weight=weight_biomass))+
    geom_density(data=dplot2, aes(x, weight=shifted_pdf_normalized), color="blue")+
  labs(x = "Values", y = "Density") +
  ggtitle("European Hake - Fitted to number, shifted to biomass"))
#only number
(numbfit <- ggplot() +
    geom_density(data=sprat, aes(log(ppmr), weight=weight_numbers))+
  geom_line(data=dplot, aes(x = x, y = density), color="red") +
  labs(x = "Values", y = "Density") +
  ggtitle("Number Density Plot from Number Distribution"))
#only biomass
(numbfitbio <- ggplot() +
    geom_density(data=sprat, aes(log(ppmr), weight=weight_biomass))+
    geom_density(data=dplot2, aes(x, weight=shifted_pdf_normalized), color="blue", alpha=0.5)+
  #geom_line(data=dplot, aes(x = x, y = density), color="red") +
  labs(x = "Values", y = "Density") +
  ggtitle("Diet Density Plot from Number Distribution"))


```

##Haddock

```{r}

sprat <- stom_df%>%filter(pred_taxa=="Melanogrammus aeglefinus")
sprat <- sprat%>%filter(nprey_perpred>0)
stomach <- sprat
stomach <- stomach%>%mutate(l=log(ppmr))%>%filter(!is.na(l))
stomach <- stomach %>% mutate(weight_numbers = nprey_perpred)
stomach$biomass <- stomach$nprey_perpred*stomach$prey_ind_weight_g
stomach <- stomach%>%filter(nprey_perpred<2000)

est <- mle_texp(stomach)
biomassestco <- est@coef

stomach <- stomach %>% mutate(weight_numbers = nprey_perpred)
grid = seq(0, 30, length.out = 200)

dist <- dtexp(grid, alpha = (biomassestco[1]), ll = biomassestco[2], ul = biomassestco[3], lr = biomassestco[4], ur = biomassestco[5])
biomassdist <- data.frame(l=grid, Density=dist)

shiftdist <- dtexp(grid, alpha = (biomassestco[1]-1), ll = biomassestco[2], ul = biomassestco[3], lr = biomassestco[4], ur = biomassestco[5])
shiftbiomassdist <- data.frame(l=grid, Density=shiftdist)

ggplot(stomach) + 
  geom_density(aes(l, weight=weight_numbers))+
  geom_density(aes(l, weight=biomass))+
 xlab("Log of predator/prey mass ratio") + 
  geom_line(aes(l, Density), data = biomassdist, color = "blue")+
  geom_line(aes(l, Density), data = shiftbiomassdist, color = "red")+
  ggtitle("Haddock - Fitted to number, shift to biomass")


```

##Horse Mackerel

```{r}

sprat <- stom_df%>%filter(pred_species=="Trachurus trachurus")
sprat <- sprat%>%filter(nprey_perpred>0)
stomach <- sprat
stomach <- stomach%>%mutate(l=log(ppmr))%>%filter(!is.na(l), l>0)
stomach <- stomach %>% mutate(weight_numbers = nprey_perpred*stomach$prey_ind_weight_g)
stomach$biomass <- stomach$nprey_perpred*stomach$prey_ind_weight_g
stomach <- stomach[-884,]

est <- mle_texp(stomach)
biomassestco <- est@coef

stomach <- stomach %>% mutate(weight_numbers = nprey_perpred)
grid = seq(0, 30, length.out = 200)

dist <- dtexp(grid, alpha = (biomassestco[1]), ll = biomassestco[2], ul = biomassestco[3], lr = biomassestco[4], ur = biomassestco[5])
biomassdist <- data.frame(l=grid, Density=dist)

shiftdist <- dtexp(grid, alpha = (biomassestco[1]+1), ll = biomassestco[2], ul = biomassestco[3], lr = biomassestco[4], ur = biomassestco[5])
shiftbiomassdist <- data.frame(l=grid, Density=shiftdist)

ggplot(stomach) + 
  geom_density(aes(l, weight=weight_numbers))+
  geom_density(aes(l, weight=biomass))+
 xlab("Log of predator/prey mass ratio") + 
  geom_line(aes(l, Density), data = biomassdist, color = "red")+
  geom_line(aes(l, Density), data = shiftbiomassdist, color = "blue")+
  ggtitle("Horse Mackerel - Fitted to biomass, shift to number")

```

##Mackerel

```{r}

sprat <- stom_df%>%filter(pred_taxa=="Scomber scombrus")
sprat <- sprat%>%filter(nprey_perpred>0)
stomach <- sprat
stomach <- stomach%>%mutate(l=log(ppmr))%>%filter(!is.na(l), l>0)
stomach <- stomach %>% mutate(weight_numbers = nprey_perpred*stomach$prey_ind_weight_g)
stomach$biomass <- stomach$nprey_perpred*stomach$prey_ind_weight_g


est <- mle_texp(stomach)
biomassestco <- est@coef

stomach <- stomach %>% mutate(weight_numbers = nprey_perpred)
grid = seq(0, 30, length.out = 200)

dist <- dtexp(grid, alpha = (biomassestco[1]), ll = biomassestco[2], ul = biomassestco[3], lr = biomassestco[4], ur = biomassestco[5])
biomassdist <- data.frame(l=grid, Density=dist)

shiftdist <- dtexp(grid, alpha = (biomassestco[1]+1), ll = biomassestco[2], ul = biomassestco[3], lr = biomassestco[4], ur = biomassestco[5])
shiftbiomassdist <- data.frame(l=grid, Density=shiftdist)

ggplot(stomach) + 
  geom_density(aes(l, weight=weight_numbers))+
  geom_density(aes(l, weight=biomass))+
 xlab("Log of predator/prey mass ratio") + 
  geom_line(aes(l, Density), data = biomassdist, color = "red")+
  geom_line(aes(l, Density), data = shiftbiomassdist, color = "blue")+
  ggtitle("Mackerel - Fitted to biomass, shift to number")


```

##Megrim

```{r}

sprat <- stom_df%>%filter(pred_taxa=="Lepidorhombus whiffiagonis")

spratnu <- repeat_elements(log(sprat$ppmr), sprat$nprey_perpred)
sprat$weight_numbers <- sprat$nprey_perpred
sprat$weight_biomass <- sprat$nprey_perpred*sprat$prey_ind_weight_g^dig
gmm <- densityMclust(spratnu, G=2)

dplot <- data.frame(x=gmm[["data"]], density=gmm[["density"]])


newspratdens <- gmm[["density"]]*exp(-dig*gmm[["data"]])
shifted_pdf_normalized <- newspratdens / sum(newspratdens) 

#making new dataframe
dplot2 <- data.frame(x=gmm[["data"]], density=shifted_pdf_normalized)


(numbfit <- ggplot() +
    geom_density(data=sprat, aes(log(ppmr), weight=weight_numbers))+
  geom_line(data=dplot, aes(x = x, y = density), color="red") +
    geom_density(data=sprat, aes(log(ppmr), weight=weight_biomass))+
    geom_density(data=dplot2, aes(x, weight=shifted_pdf_normalized), color="blue")+
  labs(x = "Values", y = "Density") +
  ggtitle("Megrim - Fitted to number, shifted to biomass"))
#only number
(numbfit <- ggplot() +
    geom_density(data=sprat, aes(log(ppmr), weight=weight_numbers))+
  geom_line(data=dplot, aes(x = x, y = density), color="red") +
  labs(x = "Values", y = "Density") +
  ggtitle("Number Density Plot from Number Distribution"))
#only biomass
(numbfitbio <- ggplot() +
    geom_density(data=sprat, aes(log(ppmr), weight=weight_biomass))+
    geom_density(data=dplot2, aes(x, weight=shifted_pdf_normalized), color="blue", alpha=0.5)+
  #geom_line(data=dplot, aes(x = x, y = density), color="red") +
  labs(x = "Values", y = "Density") +
  ggtitle("Diet Density Plot from Number Distribution"))

```

##Monkfish

```{r}

sprat <- stom_df%>%filter(pred_taxa=="Lophius piscatorius")
sprat <- sprat%>%filter(nprey_perpred>0)
stomach <- sprat
stomach <- stomach%>%mutate(l=log(ppmr))%>%filter(!is.na(l), l>0)
stomach <- stomach %>% mutate(weight_numbers = nprey_perpred*stomach$prey_ind_weight_g)
stomach$biomass <- stomach$nprey_perpred*stomach$prey_ind_weight_g


est <- mle_texp(stomach)
biomassestco <- est@coef

stomach <- stomach %>% mutate(weight_numbers = nprey_perpred)
grid = seq(0, 30, length.out = 200)

dist <- dtexp(grid, alpha = (biomassestco[1]), ll = biomassestco[2], ul = biomassestco[3], lr = biomassestco[4], ur = biomassestco[5])
biomassdist <- data.frame(l=grid, Density=dist)

shiftdist <- dtexp(grid, alpha = (biomassestco[1]+1), ll = biomassestco[2], ul = biomassestco[3], lr = biomassestco[4], ur = biomassestco[5])
shiftbiomassdist <- data.frame(l=grid, Density=shiftdist)

ggplot(stomach) + 
  geom_density(aes(l, weight=weight_numbers))+
 xlab("Log of predator/prey mass ratio") + 
    geom_line(aes(l, Density), data = shiftbiomassdist, color = "blue")+
  ggtitle("Monkfish - Fitted biomass")
ggplot(stomach) + 
  geom_density(aes(l, weight=biomass))+
 xlab("Log of predator/prey mass ratio") + 
  geom_line(aes(l, Density), data = biomassdist, color = "red")+
  ggtitle("Monkfish - shifted to number")

```

##Norway pout 

```{r}

sprat <- stom_df%>%filter(pred_taxa=="Trisopterus esmarkii")
sprat <- sprat%>%filter(nprey_perpred>0)
stomach <- sprat
stomach <- stomach%>%mutate(l=log(ppmr))%>%filter(!is.na(l), l>0)
stomach <- stomach %>% mutate(weight_numbers = nprey_perpred*stomach$prey_ind_weight_g)
stomach$biomass <- stomach$nprey_perpred*stomach$prey_ind_weight_g


est <- mle_texp(stomach)
biomassestco <- est@coef

stomach <- stomach %>% mutate(weight_numbers = nprey_perpred)
grid = seq(0, 30, length.out = 200)

dist <- dtexp(grid, alpha = (biomassestco[1]), ll = biomassestco[2], ul = biomassestco[3], lr = biomassestco[4], ur = biomassestco[5])
biomassdist <- data.frame(l=grid, Density=dist)

shiftdist <- dtexp(grid, alpha = (biomassestco[1]+1), ll = biomassestco[2], ul = biomassestco[3], lr = biomassestco[4], ur = biomassestco[5])
shiftbiomassdist <- data.frame(l=grid, Density=shiftdist)

ggplot(stomach) + 
  geom_density(aes(l, weight=weight_numbers))+
  geom_density(aes(l, weight=biomass))+
 xlab("Log of predator/prey mass ratio") + 
  geom_line(aes(l, Density), data = biomassdist, color = "red")+
  geom_line(aes(l, Density), data = shiftbiomassdist, color = "blue")+
  ggtitle("Norway Pout - Fitted to biomass, shift to number")

```

##Plaice

```{r}

sprat <- stom_df%>%filter(pred_taxa=="Pleuronectes platessa")

spratnu <- repeat_elements(log(sprat$ppmr), sprat$nprey_perpred)
sprat$weight_numbers <- sprat$nprey_perpred
sprat$weight_biomass <- sprat$nprey_perpred*sprat$prey_ind_weight_g^dig
gmm <- densityMclust(spratnu, G=2)

dplot <- data.frame(x=gmm[["data"]], density=gmm[["density"]])


newspratdens <- gmm[["density"]]*exp(-dig*gmm[["data"]])
shifted_pdf_normalized <- newspratdens / sum(newspratdens) 

#making new dataframe
dplot2 <- data.frame(x=gmm[["data"]], density=shifted_pdf_normalized)


(numbfit <- ggplot() +
    geom_density(data=sprat, aes(log(ppmr), weight=weight_numbers))+
  geom_line(data=dplot, aes(x = x, y = density), color="red") +
    geom_density(data=sprat, aes(log(ppmr), weight=weight_biomass))+
    geom_density(data=dplot2, aes(x, weight=shifted_pdf_normalized), color="blue")+
  labs(x = "Values", y = "Density") +
  ggtitle("Plaice - Fitted to number, shifted to biomass"))
#only number
(numbfit <- ggplot() +
    geom_density(data=sprat, aes(log(ppmr), weight=weight_numbers))+
  geom_line(data=dplot, aes(x = x, y = density), color="red") +
  labs(x = "Values", y = "Density") +
  ggtitle("Number Density Plot from Number Distribution"))
#only biomass
(numbfitbio <- ggplot() +
    geom_density(data=sprat, aes(log(ppmr), weight=weight_biomass))+
    geom_density(data=dplot2, aes(x, weight=shifted_pdf_normalized), color="blue", alpha=0.5)+
  #geom_line(data=dplot, aes(x = x, y = density), color="red") +
  labs(x = "Values", y = "Density") +
  ggtitle("Diet Density Plot from Number Distribution"))

```

##Poor Cod

```{r}
sprat <- stom_df%>%filter(pred_taxa=="Trisopterus minutus")
sprat <- sprat%>%filter(nprey_perpred>0)
stomach <- sprat
stomach <- stomach%>%mutate(l=log(ppmr))%>%filter(!is.na(l), l>0)
stomach <- stomach %>% mutate(weight_numbers = nprey_perpred)
stomach$biomass <- stomach$nprey_perpred*stomach$prey_ind_weight_g


est <- mle_texp(stomach)
biomassestco <- est@coef

stomach <- stomach %>% mutate(weight_numbers = nprey_perpred)
grid = seq(0, 30, length.out = 200)

dist <- dtexp(grid, alpha = (biomassestco[1]), ll = biomassestco[2], ul = biomassestco[3], lr = biomassestco[4], ur = biomassestco[5])
biomassdist <- data.frame(l=grid, Density=dist)

shiftdist <- dtexp(grid, alpha = (biomassestco[1]-1), ll = biomassestco[2], ul = biomassestco[3], lr = biomassestco[4], ur = biomassestco[5])
shiftbiomassdist <- data.frame(l=grid, Density=shiftdist)

ggplot(stomach) + 
  geom_density(aes(l, weight=weight_numbers))+
  geom_density(aes(l, weight=biomass))+
 xlab("Log of predator/prey mass ratio") + 
  geom_line(aes(l, Density), data = biomassdist, color = "red")+
  geom_line(aes(l, Density), data = shiftbiomassdist, color = "blue")+
  ggtitle("Poor Cod - Fitted to biomass, shift to number")

```

##Sole

```{r}
sprat <- stom_df%>%filter(pred_taxa=="Solea solea")

spratnu <- repeat_elements(log(sprat$ppmr), sprat$nprey_perpred)
sprat$weight_numbers <- sprat$nprey_perpred
sprat$weight_biomass <- sprat$nprey_perpred*sprat$prey_ind_weight_g^dig
gmm <- densityMclust(spratnu, G=2)

dplot <- data.frame(x=gmm[["data"]], density=gmm[["density"]])


newspratdens <- gmm[["density"]]*exp(-dig*gmm[["data"]])
shifted_pdf_normalized <- newspratdens / sum(newspratdens) 

#making new dataframe
dplot2 <- data.frame(x=gmm[["data"]], density=shifted_pdf_normalized)


(numbfit <- ggplot() +
    geom_density(data=sprat, aes(log(ppmr), weight=weight_numbers))+
  geom_line(data=dplot, aes(x = x, y = density), color="red") +
    geom_density(data=sprat, aes(log(ppmr), weight=weight_biomass))+
    geom_density(data=dplot2, aes(x, weight=shifted_pdf_normalized), color="blue")+
  labs(x = "Values", y = "Density") +
  ggtitle("Sole - Fitted to number, shifted to biomass"))
#only number
(numbfit <- ggplot() +
    geom_density(data=sprat, aes(log(ppmr), weight=weight_numbers))+
  geom_line(data=dplot, aes(x = x, y = density), color="red") +
  labs(x = "Values", y = "Density") +
  ggtitle("Number Density Plot from Number Distribution"))
#only biomass
(numbfitbio <- ggplot() +
    geom_density(data=sprat, aes(log(ppmr), weight=weight_biomass))+
    geom_density(data=dplot2, aes(x, weight=shifted_pdf_normalized), color="blue", alpha=0.5)+
  #geom_line(data=dplot, aes(x = x, y = density), color="red") +
  labs(x = "Values", y = "Density") +
  ggtitle("Diet Density Plot from Number Distribution"))

```

##Sprat

```{r}

sprat <- stom_df%>%filter(pred_taxa=="Sprattus sprattus")
spratnu <- repeat_elements(log(sprat$ppmr), sprat$nprey_perpred)
sprat$weight_numbers <- sprat$nprey_perpred
sprat$weight_biomass <- sprat$nprey_perpred*sprat$prey_ind_weight_g^dig
gmm <- densityMclust(spratnu, G=3)

dplot <- data.frame(x=gmm[["data"]], density=gmm[["density"]])


newspratdens <- gmm[["density"]]*exp(-dig*gmm[["data"]])
shifted_pdf_normalized <- newspratdens / sum(newspratdens) 

#making new dataframe
dplot2 <- data.frame(x=gmm[["data"]], density=shifted_pdf_normalized)


(numbfit <- ggplot() +
    geom_density(data=sprat, aes(log(ppmr), weight=weight_numbers))+
  geom_line(data=dplot, aes(x = x, y = density), color="red") +
    geom_density(data=sprat, aes(log(ppmr), weight=weight_biomass))+
    geom_density(data=dplot2, aes(x, weight=shifted_pdf_normalized), color="blue")+
  labs(x = "Values", y = "Density") +
  ggtitle("Sole - Fitted to number, shifted to biomass"))
#only number
(numbfit <- ggplot() +
    geom_density(data=sprat, aes(log(ppmr), weight=weight_numbers))+
  geom_line(data=dplot, aes(x = x, y = density), color="red") +
  labs(x = "Values", y = "Density") +
  ggtitle("Number Density Plot from Number Distribution"))
#only biomass
(numbfitbio <- ggplot() +
    geom_density(data=sprat, aes(log(ppmr), weight=weight_biomass))+
    geom_density(data=dplot2, aes(x, weight=shifted_pdf_normalized), color="blue", alpha=0.5)+
  #geom_line(data=dplot, aes(x = x, y = density), color="red") +
  labs(x = "Values", y = "Density") +
  ggtitle("Diet Density Plot from Number Distribution"))
```


##Spurdog


```{r}

sprat <- stom_df%>%filter(pred_taxa=="Squalus acanthias")
sprat <- sprat%>%filter(nprey_perpred<200)
spratnu <- repeat_elements(log(sprat$ppmr), sprat$nprey_perpred)
sprat$weight_numbers <- sprat$nprey_perpred
sprat$weight_biomass <- sprat$nprey_perpred*sprat$prey_ind_weight_g^dig
gmm <- densityMclust(spratnu, G=2)

dplot <- data.frame(x=gmm[["data"]], density=gmm[["density"]])


newspratdens <- gmm[["density"]]*exp(-dig*gmm[["data"]])
shifted_pdf_normalized <- newspratdens / sum(newspratdens) 

#making new dataframe
dplot2 <- data.frame(x=gmm[["data"]], density=shifted_pdf_normalized)


(numbfit <- ggplot() +
    geom_density(data=sprat, aes(log(ppmr), weight=weight_numbers))+
  geom_line(data=dplot, aes(x = x, y = density), color="red") +
    geom_density(data=sprat, aes(log(ppmr), weight=weight_biomass))+
    geom_density(data=dplot2, aes(x, weight=shifted_pdf_normalized), color="blue")+
  labs(x = "Values", y = "Density") +
  ggtitle("Spurdog - Fitted to number, shifted to biomass"))
#only number
(numbfit <- ggplot() +
    geom_density(data=sprat, aes(log(ppmr), weight=weight_numbers))+
  geom_line(data=dplot, aes(x = x, y = density), color="red") +
  labs(x = "Values", y = "Density") +
  ggtitle("Number Density Plot from Number Distribution"))
#only biomass
(numbfitbio <- ggplot() +
    geom_density(data=sprat, aes(log(ppmr), weight=weight_biomass))+
    geom_density(data=dplot2, aes(x, weight=shifted_pdf_normalized), color="blue", alpha=0.5)+
  #geom_line(data=dplot, aes(x = x, y = density), color="red") +
  labs(x = "Values", y = "Density") +
  ggtitle("Diet Density Plot from Number Distribution"))
```